#SPDX-License-Identifier: MIT
---
namespace: juli3nk
name: ai
version: 1.0.0

readme: README.md

authors:
- Julien K. (https://github.com/juli3nk)

description: Ansible collection for AI management

license:
- MIT
license_file: 'LICENSE'

tags:
  - ai
  - openclaw
  - cursor-cli

dependencies: {}

repository: https://github.com/juli3nk/ansible-collection-ai
documentation: https://github.com/juli3nk/ansible-collection-ai
homepage: https://github.com/juli3nk/ansible-collection-ai
issues: https://github.com/juli3nk/ansible-collection-ai/issues

build_ignore:
  - .config
  - .github
  - .gitignore
  - changelogs
  - roles/*/molecule
  - tests
  - '*.tar.gz'
